version: "2"

services:

  elasticsearch-master:
    build: ./elasticsearch
    restart: always
    environment:
    - mode=master
    - nodes=["elasticsearch-master", "elasticsearch-slave1", "elasticsearch-slave2"]
    networks:
      - web
    ports:
      - 9200:9200

  elasticsearch-slave1:
    build: ./elasticsearch
    restart: always
    environment:
      - mode=slave
      - nodes=["elasticsearch-master", "elasticsearch-slave1", "elasticsearch-slave2"]
    networks:
      - web

  elasticsearch-slave2:
    build: ./elasticsearch
    restart: always
    environment:
      - mode=slave
      - nodes=["elasticsearch-master", "elasticsearch-slave1", "elasticsearch-slave2"]
    networks:
      - web

  kibana:
    build: ./kibana
    restart: always
    ports:
      - 5601:5601
    networks:
      - web

  flight-delays:
    build: ./flight-delays
    networks:
      - web
    environment:
      - source=/delays/airline_delay_causes.csv
      - elasticsearch_url=http://elasticsearch-master:9200

networks:
  web:
